run:
  tests: false
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 12
    skip-tests: true
  gofumpt:
    extra-rules: true
  depguard:
    rules:
      deprecated:
        deny:
          - pkg: pkg/errors

linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - gomnd
    - ireturn
    - nlreturn
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
  exclude:
    - "ST1000: at least one file in a package should have a package comment"